services:
  app:
    image: ghcr.io/navitronic/limb:latest
    volumes:
      - .:/site
    command: php bin/console site:serve --source=/site --host=0.0.0.0 --port=4000
    ports:
      - "4000:4000"
